nameSuffix: -big
bases:
- ../base

commonLabels:
  app: memcached-mutilate-big

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - threads=3
  - load_records=1500000
  - records=1500000  # 1.5M
  - value=80000      # 80kB * 1.5M  <= 120GB
  - qps=15000        # 15k

patchesStrategicMerge:
  - resources.yaml
