nameSuffix: -big
bases:
- ../base

commonLabels:
  app: redis-memtier-big
  size: big

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=50
    - threads=8
    - keymaximum_gen=40000000    # 40M
    - keymaximum_load=40000000    # 400k
    - datasize=1024          # 45-50GB

patchesStrategicMerge:
  - resources.yaml
