{
 "title": "2LM score2 dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "History of number of apps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(app_req)" }
   ]
  },
  {
   "title": "app_req",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 8 },
   "targets": [
    { "expr": "app_req", "legendFormat": "{{app}} | {{dim}}" }
   ]
  },
  {
   "title": "node_capacity",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 8 },
   "targets": [
    { "expr": "node_capacity", "legendFormat": "{{node}} | {{dim}}" }
   ]
  },
  {
   "title": "profile_nodes_by_mem{memory=\"2lm\"}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 22 },
   "targets": [
    {
     "expr": "profile_nodes_by_mem{memory=\"2lm\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "profile_app_by_mem_norm",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 27 },
   "targets": [
    { "expr": "profile_app_by_mem_norm", "legendFormat": "{{app}} | {{index}}" }
   ]
  },
  {
   "title": "profile_nodes_by_mem{memory=\"1lm\"}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 27 },
   "targets": [
    {
     "expr": "profile_nodes_by_mem{memory=\"1lm\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "profile_app_by_mem_norm",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 19, "w": 4, "x": 9, "y": 32 },
   "targets": [
    { "expr": "profile_app_2lm_score2_max", "legendFormat": "{{app}} | SCORE(max)" }
   ]
  },
  {
   "title": "Legend",
   "type": "text",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 32 },
   "content": "\nDefintion | Unit | Equation | Description\n------------ | ---- | ---------| ----\n**mem_density** | `[cpu/GB]`  | `cpu` / `mem` | higher is better \n**mem_intensity (read/write)** | `[GB/GB]` | `mbw` / `mem` | lower is better \n**mem_utilization** | `[GB/GB]` | `wss` / `mem` | lower is better\n**SCORE**    | |  `cpu_density` - `max`(`mem_intensity`, `mem_utilization`) | higher is better\n\n\n\n\n\n\n\n"
  }
 ]
}