loggers:
  "wca.extra.numa_allocator": "trace"
  "wca.cgroups_allocations": "trace"
  "wca": "info"
runner: !AllocationRunner
  measurement_runner: !MeasurementRunner
    interval: 5
    node: !MesosNode
      mesos_agent_endpoint: 'http://127.0.0.1:5051'
      timeout: 5

    enable_derived_metrics: true

    # Metrics to files
    metrics_storage: !LogStorage
      output_filename: metrics.prom
      overwrite: true

    task_label_generators:
      aurora_instance: !TaskLabelRegexGenerator
        pattern: '.*-(\d+)-.{36}'
        repl: '\1'  # first match group
        source: 'task_id' #default

    extra_labels:
      node: !Env HOSTNAME

  allocator: !NUMAAllocator
    loop_min_task_balance: 0.0
    free_space_check: false
    #---
    migrate_pages: true
    migrate_pages_min_task_balance: 0.95
    #---
    cgroups_memory_binding: false
    cgroups_memory_migrate: false
    #---
    algorithm: 'fill_biggest_first'
    #---
    dryrun: false

  allocations_storage: !LogStorage
    output_filename: allocations.prom
    overwrite: true
  anomalies_storage: !LogStorage
    output_filename: anomalies.prom
    overwrite: true
