runner: !MeasurementRunner
  event_names:
    - task_instructions
    - task_cycles
    - task_cache_references
    - task_cache_misses
    - instructionraw__rC000
  enable_derived_metrics: true
  node: !StaticNode
    tasks:
      - task1
