{
 "title": "WCA Scheduler Main View",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "query": "label_values(wca_up, nodename)" },
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage ( requested / capacity ) ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(sum(task_requested_cpus{node=~\"$node\"}) by (nodename) or (sum(wca_up{node=~\"$node\"}) by (nodename)/sum(wca_up{node=~\"$node\"}) by (nodename) - 1)) / sum(platform_topology_cpus{node=~\"$node\"}) by (nodename)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory usage ( requested / capacity ) ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "(sum(task_requested_mem_bytes{node=~\"$node\"}) by (nodename) or (sum(wca_up{node=~\"$node\"}) by (nodename)/sum(wca_up{node=~\"$node\"}) by (nodename) - 1)) / sum(node_memory_MemTotal_bytes{nodename=~\"$node\"}) by (nodename)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Number of pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(wca_tasks{node=~\"$node\"}) by (nodename)",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload placement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apps per node (current)",
     "type": "yesoreyeram-boomtable-panel",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "appnode_count{node=~\"$node\"}",
       "legendFormat": "{{app}} | {{node}}"
      }
     ]
    }
   ]
  }
 ]
}