{
 "title": "Intel WCA Score dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Score",
    "query": "0.5,1.0,1.5,2.0,2.5,3.0,4.0,5.0,6.0,10.0"
   }
  ]
 },
 "panels": [
  {
   "title": "How many workloads profiling data is available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(app_req{dim=\"cpu\"}) by (dim)",
     "legendFormat": "profiled_count"
    }
   ]
  },
  {
   "title": "app_req",
   "type": "yesoreyeram-boomtable-panel",
   "description": "Application approximated resources peak requirements.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expr": "app_req", "legendFormat": "{{app}} | {{dim}}" }
   ]
  },
  {
   "title": "node_capacity",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 9 },
   "targets": [
    { "expr": "node_capacity", "legendFormat": "{{node}} | {{dim}}" }
   ]
  },
  {
   "title": "Legend",
   "type": "text",
   "gridPos": { "h": 16, "w": 8, "x": 15, "y": 9 },
   "options": {
    "content": "\nDefintion | Unit | Equation | Description\n------------ | ---- | ---------| ----\n**cpu_ratio** | `[cpu/GB]`  | `cpu` / `mem` | app resources \n**mbw_flat_ratio** | `[GBs/GB]` | `mbw_flat` / `mem` | app resources \n**wss_ratio** | `[GB/GB]` | `wss` / `mem` | app resources\n**2lm_cpu_ratio** | `[cpu/GB]`  | `cpu` / `mem` | 2LM node resources\n**2lm_mbw_flat_ratio** | `[GBs/GB]` | `mbw_flat` / `mem` | 2LM node resources \n**2lm_wss_ratio** | `[GB/GB]` | `wss` / `mem` | 2LM node resources\n**cpu_ratio_2lmscaled** | `None`  | `cpu_ratio` / `2lm_cpu_ratio` | app resources shape in comparison to 2LM resources shape\n**mbw_flat_ratio_2lmscaled** | `None` | `mbw_ratio` / `2lm_mbw_ratio` | app resources shape in comparison to 2LM resources shape \n**wss_ratio_2lmscaled** | `None` | `wss_ratio` / `2lm_wss_ratio` | app resources shape in comparison to 2LM resources shape\n**score** | `None` | max(`cpu_ratio_2lmscaled`, `mbw_flat_ratio_2lmscaled`, `wss_ratio_2lmscaled`) | lower is better\n\n\n\n\n\n\n\n"
   },
   "content": "\nDefintion | Unit | Equation | Description\n------------ | ---- | ---------| ----\n**cpu_ratio** | `[cpu/GB]`  | `cpu` / `mem` | app resources \n**mbw_flat_ratio** | `[GBs/GB]` | `mbw_flat` / `mem` | app resources \n**wss_ratio** | `[GB/GB]` | `wss` / `mem` | app resources\n**2lm_cpu_ratio** | `[cpu/GB]`  | `cpu` / `mem` | 2LM node resources\n**2lm_mbw_flat_ratio** | `[GBs/GB]` | `mbw_flat` / `mem` | 2LM node resources \n**2lm_wss_ratio** | `[GB/GB]` | `wss` / `mem` | 2LM node resources\n**cpu_ratio_2lmscaled** | `None`  | `cpu_ratio` / `2lm_cpu_ratio` | app resources shape in comparison to 2LM resources shape\n**mbw_flat_ratio_2lmscaled** | `None` | `mbw_ratio` / `2lm_mbw_ratio` | app resources shape in comparison to 2LM resources shape \n**wss_ratio_2lmscaled** | `None` | `wss_ratio` / `2lm_wss_ratio` | app resources shape in comparison to 2LM resources shape\n**score** | `None` | max(`cpu_ratio_2lmscaled`, `mbw_flat_ratio_2lmscaled`, `wss_ratio_2lmscaled`) | lower is better\n\n\n\n\n\n\n\n"
  },
  {
   "title": "resource_ratio_2lmscaled",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "profile_app_by_mem_norm{index=~\"cpu|mbw_flat|wss\"} - 0.02",
     "legendFormat": "{{app}} | {{index}}"
    }
   ]
  },
  {
   "title": "SCORE",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 20 },
   "targets": [
    { "expr": "profile_app_score_max", "legendFormat": "{{app}} | SCORE(max)" }
   ]
  },
  {
   "title": "Calculated required number of PMEM nodes for choosen Score",
   "type": "singlestat",
   "description": "This is simple heuristic which tries to approximates how many PMEM nodes are needed on the cluster for all applications with score less than choosen in the top of the dashboard. We sum up the memory used of all applications multiplied by their score. In the end, we divide by PMEM size.",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ceil((sum(abs(profile_app_score_max < $Score) * on(app) app_count * on(app) app_mem) )  / 1000 )"
    }
   ]
  }
 ]
}