{
 "title": "Workload 2LM profiling",
 "tags": [ "2lm" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": "label_values(wca_up, nodename)" },
   { "name": "app", "query": "label_values(task_up, app)" }
  ]
 },
 "panels": [
  {
   "title": "Task level MBW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "all_pf_data__l3_miss_any_snoop + demand_data__l3_miss_any_snoop",
     "type": "graph",
     "description": "rate(offcore_response__all_pf_data__l3_miss_any_snoop__rB701003FBC000490[30s]) * 64 / 1e9 + rate(offcore_response__demand_data__l3_miss_any_snoop__rB701003FBC000001[30s]) * 64 / 1e9",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(offcore_response__all_pf_data__l3_miss_any_snoop__rB701003FBC000490{node=~\"$node\", app=~\"$app\"}[30s]) * 64 + rate(offcore_response__demand_data__l3_miss_any_snoop__rB701003FBC000001{node=~\"$node\", app=~\"$app\"}[30s]) * 64",
       "legendFormat": "{{app}}-{{node}}"
      }
     ]
    },
    {
     "title": "l2_lines_in_all__r1ff1",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(l2_lines_in_all__r1ff1{node=~\"$node\", app=~\"$app\"}[30s]) * 64",
       "legendFormat": "{{app}}--{{node}}"
      }
     ]
    },
    {
     "title": "l2_trans_l2_wb__r40f0",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(l2_trans_l2_wb__r40f0{node=~\"$node\", app=~\"$app\"}[30s]) * 64",
       "legendFormat": "{{app}}--{{node}}"
      }
     ]
    },
    {
     "title": "mem_load_l3_miss_retired_remote_dram__r02d3",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(mem_load_l3_miss_retired_remote_dram__r02d3{node=~\"$node\", app=~\"$app\"}[30s]) * 64",
       "legendFormat": "{{app}}--{{node}}"
      }
     ]
    },
    {
     "title": "mem_inst_retired_all_loads__r81d0",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(mem_inst_retired_all_loads__r81d0{node=~\"$node\", app=~\"$app\"}[30s]) * 64",
       "legendFormat": "{{app}}--{{node}}"
      }
     ]
    },
    {
     "title": "mem_inst_retired_all_stores__r82d0",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(mem_inst_retired_all_stores__r82d0{node=~\"$node\", app=~\"$app\"}[30s]) * 64",
       "legendFormat": "{{app}}--{{node}}"
      }
     ]
    },
    {
     "title": "mem_load_l3_miss_retired_local_dram__r01d3",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(mem_load_l3_miss_retired_local_dram__r01d3{node=~\"$node\", app=~\"$app\"}[30s]) * 64",
       "legendFormat": "{{app}}--{{node}}"
      }
     ]
    }
   ]
  },
  { "title": "Task level R/W MBW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "[R/W ratio] DRAM Platform",
   "type": "graph",
   "description": "READS/WRITES DRAM PLATFORM\n\nsum(platform_dram_reads_bytes_per_second{node=~\"$node\"}) by (node) / sum(platform_dram_writes_bytes_per_second{node=~\"$node\"}) by (node)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(platform_dram_reads_bytes_per_second{node=~\"$node\"}) by (node) / sum(platform_dram_writes_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "[R/W ratio] DRAM+PMM Platform",
   "type": "graph",
   "description": "READS/WRITES DRAM PLATFORM\n\nsum(platform_dram_reads_bytes_per_second{node=~\"$node\"}) by (node) / sum(platform_dram_writes_bytes_per_second{node=~\"$node\"}) by (node)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(platform_dram_reads_bytes_per_second{node=~\"$node\"}) by (node) + sum(platform_pmm_reads_bytes_per_second{node=~\"$node\"}) by (node)) / (sum(platform_dram_writes_bytes_per_second{node=~\"$node\"}) by (node) + sum(platform_pmm_writes_bytes_per_second{node=~\"$node\"}) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "RDT task level",
   "type": "graph",
   "description": "delta == difference between what show platform and rdt tasks\nplatform_dram_total_bytes_per_second\ntask_mem_bandwidth_bytes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(task_mem_bandwidth_bytes{node=~\"$node\", app=~\"$app\"}[30s])",
     "legendFormat": "{{app}}--{{node}}"
    }
   ]
  },
  {
   "title": "RDT MEMBW and delta(PLATFORM, RDT)",
   "type": "graph",
   "description": "delta == difference between what show platform and rdt tasks\nplatform_dram_total_bytes_per_second\ntask_mem_bandwidth_bytes",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_mem_bandwidth_bytes{node=~\"$node\"}[30s])) by (node)  - sum(platform_dram_total_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "delta--{{node}}"
    },
    {
     "expr": "sum(rate(task_mem_bandwidth_bytes{node=~\"$node\"}[30s])) by (node)",
     "legendFormat": "rdt--{{node}}"
    },
    { "expr": "0" },
    {
     "expr": "sum(platform_dram_total_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "platform--{{node}}"
    }
   ]
  },
  {
   "title": "DRAM Platform memory bandwidth GB/s ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(platform_dram_total_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "DRAM[{{node}}]"
    }
   ]
  },
  {
   "title": "[WRITES] DRAM Platform memory bandwidth GB/s ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(platform_dram_writes_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "DRAM[{{node}}]"
    }
   ]
  },
  {
   "title": "[READS] DRAM Platform memory bandwidth GB/s ",
   "type": "graph",
   "description": "sum(platform_dram_reads_bytes_per_second{node=~\"$node\"}) by (node)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(platform_dram_reads_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "DRAM[{{node}}]"
    }
   ]
  },
  {
   "title": "tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wca_tasks{node=~\"$node\"}",
     "legendFormat": "tasks[{{node}}]"
    }
   ]
  },
  {
   "title": "PMM Platform memory bandwidth GB/s ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(platform_pmm_total_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "PMM[{{node}}]"
    }
   ]
  },
  {
   "title": "[WRITES] PMEM Platform memory bandwidth GB/s ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(platform_pmm_writes_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "PMEM[{{node}}]"
    }
   ]
  },
  {
   "title": "[READS] PMEM Platform memory bandwidth GB/s ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(platform_pmm_reads_bytes_per_second{node=~\"$node\"}) by (node)",
     "legendFormat": "PMEM[{{node}}]"
    }
   ]
  },
  {
   "title": "[R/W ratio] Task level - scaled task_offcore_requests_demand_data_rd/rfo",
   "type": "graph",
   "description": "rd/rfo",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_offcore_requests_demand_data_rd{node=~\"$node\"}[30s])) by (node) + sum(rate(task_offcore_requests_demand_rfo{node=~\"$node\"}[30s])) by (node) ) / sum(rate(task_offcore_requests_demand_rfo{node=~\"$node\"}[30s])) by (node)"
    }
   ]
  },
  {
   "title": "filter algorithm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requsted CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(task_requested_cpus{node=~\"$node\"}) by (nodename)",
       "legendFormat": "requested--{{nodename}}"
      },
      {
       "expr": "sum(platform_topology_cpus{node=~\"$node\"}) by (nodename)",
       "legendFormat": "available--{{nodename}}"
      }
     ]
    },
    {
     "title": "Requsted MEM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(task_requested_mem_bytes{node=~\"$node\"}) by (nodename)",
       "legendFormat": "requested--{{nodename}}"
      }
     ]
    },
    {
     "title": "sum RSS by app ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(task_mem_usage_bytes{node=~\"$node\", app=~\"$app\"}) by (app,node)",
       "legendFormat": "RSS:{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "WSS [%]",
     "type": "graph",
     "description": "0.2 set as limit",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(task_wss_referenced_bytes{node=~\"$node\"}) by (node) /  sum(platform_dimm_total_size_bytes{dimm_type=\"ram\", node=~\"$node\"}) by (node))  or sum(platform_dimm_total_size_bytes{dimm_type=\"ram\", node=~\"$node\"}) by (node) * 0"
      },
      { "expr": "0.2", "legendFormat": "limit-wca-scheduler" }
     ]
    },
    {
     "title": "WSS [GB]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(task_wss_referenced_bytes{node=~\"$node\"}) by (node)"
      },
      {}
     ]
    },
    {
     "title": "DRAM size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 1, "x": 9, "y": 32 },
     "targets": [
      {
       "expr": "sum(platform_dimm_total_size_bytes{dimm_type=\"ram\", node=~\"$node\"}) by (node)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "MEMORY",
     "type": "stat",
     "gridPos": { "h": 8, "w": 1, "x": 10, "y": 32 },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{nodename=~\"$node\"}) by (nodename)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "MEMBW_FLAT vs MAX (wca_scheduler)",
     "type": "graph",
     "description": "0.7 set as limit",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(sum(platform_dram_reads_bytes_per_second{node=~\"$node\"}) by (node) + sum(platform_pmm_reads_bytes_per_second{node=~\"$node\"}) by (node)) + (sum(platform_dram_writes_bytes_per_second{node=~\"$node\"}) by (node) + sum(platform_pmm_writes_bytes_per_second{node=~\"$node\"}) by (node)) * 3.7 "
      },
      {
       "expr": "sum(platform_nvdimm_read_bandwidth_bytes_per_second{nodename=~\"node101\"}) by (nodename) * 0.7",
       "legendFormat": "wca-scheduler-limit--node101"
      }
     ]
    },
    {
     "title": "tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wca_tasks{node=~\"$node\"}",
       "legendFormat": "tasks[{{node}}]"
      }
     ]
    },
    {
     "title": "avg APM latency of single instnace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (app,node) (apm_latency{node=~\"$node\", app=~\"$app\"})",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "avg APM throughput of single instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (app,node) (apm_throughput{node=~\"$node\", app=~\"$app\"})",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "per app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "avg task_mem_bandwidth_remote_bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(task_mem_bandwidth_remote_bytes{node=~\"$node\", app=~\"$app\"}[1m])) by (app,node)",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "avg task_mem_bandwidth_remote_bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(task_mem_bandwidth_remote_bytes{node=~\"$node\", app=~\"$app\"}[1m])) by (app,node)",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "avg WSS per app instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(task_wss_referenced_bytes{node=~\"$node\", app=~\"$app\"}[15s])) by (app,node)",
       "legendFormat": "WSS-{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "avg task_mem_bandwidth_bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(task_mem_bandwidth_bytes{node=~\"$node\", app=~\"$app\"}[1m])) by (app,node)",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "avg task_mem_bandwidth_local_bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(task_mem_bandwidth_local_bytes{node=~\"$node\", app=~\"$app\"}[1m])) by (app,node)",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "avg task_mem_bandwidth_remote_bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(task_mem_bandwidth_remote_bytes{node=~\"$node\", app=~\"$app\"}[1m])) by (app,node)",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "[R/W ratio] Task level, uncore metrics",
     "type": "graph",
     "description": "rd/rfo",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(task_offcore_requests_demand_data_rd{node=~\"$node\"}[30s])) by (node)) / (sum(rate(task_offcore_requests_demand_data_rfo{node=~\"$node\"}[30s])) by (node))"
      },
      {
       "expr": "(sum(rate(task_offcore_requests_l3_miss_demand_data_rd{node=~\"$node\"}[30s])) by (node) + sum(rate(task_offcore_requests_demand_rfo{node=~\"$node\"}[30s])) by (node) ) / sum(rate(task_offcore_requests_demand_rfo{node=~\"$node\"}[30s])) by (node)"
      }
     ]
    },
    {
     "title": "[WRITES] rate(task_offcore_requests_demand_data_rd)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_offcore_requests_demand_rfo{node=~\"$node\", app=~\"$app\"}[30s])) by (app,node) * 64",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "avg APM latency of single instnace",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (app,node) (apm_latency{node=~\"$node\", app=~\"$app\"})",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "RDT MEMBW and delta(PLATFORM, RDT)",
     "type": "graph",
     "description": "delta == difference between what show platform and rdt tasks\nplatform_dram_total_bytes_per_second\ntask_mem_bandwidth_bytes",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_mem_bandwidth_bytes{node=~\"$node\", app=~\"$app\"}[30s])) by (node)  - sum(platform_dram_total_bytes_per_second{node=~\"$node\"}) by (node)",
       "legendFormat": "delta--{{node}}"
      },
      {
       "expr": "sum(rate(task_mem_bandwidth_bytes{node=~\"$node\", app=~\"$app\"}[30s])) by (node)",
       "legendFormat": "rdt--{{node}}"
      }
     ]
    },
    {
     "title": "tasks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wca_tasks{node=~\"$node\"}",
       "legendFormat": "tasks[{{node}}]"
      }
     ]
    },
    {
     "title": "platform_mem_usage_bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(platform_mem_usage_bytes{node=~\"$node\"}) by (node)",
       "legendFormat": "total_usage[{{node}}]"
      }
     ]
    },
    {
     "title": "sum WSS by app ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(task_wss_referenced_bytes{node=~\"$node\", app=~\"$app\"}[15s]) ) by (app,node)",
       "legendFormat": "WSS:{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "DRAM hit raito",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(platform_dram_hit_ratio{node=~\"$node\"}) by (node)",
       "legendFormat": "[{{node}}]"
      }
     ]
    },
    {
     "title": "[READS] rate(task_offcore_requests_demand_data_rd) ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_offcore_requests_demand_data_rd{node=~\"$node\", app=~\"$app\"}[30s])) by (app,node) * 64 ",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "Average throughput",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg by (app,node) (apm_throughput{node=~\"$node\", app=~\"$app\"})"
      }
     ]
    },
    {
     "title": "avg APM throughput of single instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (app,node) (apm_throughput{node=~\"$node\", app=~\"$app\"})",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "IPC",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(task_instructions{node=~\"$node\", app=~\"$app\"}[15s]) / rate(task_cycles{node=~\"$node\", app=~\"$app\"}[15s])) by (app, node)",
       "legendFormat": "{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "sum RSS by app ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(task_mem_usage_bytes{node=~\"$node\", app=~\"$app\"}[15s]) ) by (app,node)",
       "legendFormat": "RSS:{{app}}[{{node}}]"
      }
     ]
    },
    {
     "title": "node freq (avg)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "avg(node_cpu_scaling_frequency_hertz{nodename=~\"$node\"}) by (nodename)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}